name: Publish SDK

on:
  push:
    branches:
      - main

jobs:
  publish-js:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm test
      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      - run: npm version patch
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLIC_NPM_TOKEN }}
      - name: Push version changes
        run: |
          git push 